version: '3.1'

services:
  mysql:
    image: mysql:8.0.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker-dev
      MYSQL_DATABASE: mbs_project_2022 
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      UPLOAD_LIMIT: 300000000
    links:
      - mysql:db